version: "3.7"

networks:
  skeleton-docker.network:
    driver: bridge

services:
  php:
    build: ./docker/php
    restart: always
    container_name: skeleton-docker.php
    tty: true
    depends_on:
      - mysql
    networks:
      - skeleton-docker.network
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/app.dev

  nginx:
    build: ./docker/nginx
    container_name: skeleton-docker.nginx
    restart: always
    tty: true
    depends_on:
      - php
      - mysql
    ports:
      - '8080:80'
      - "433:433"
    volumes:
      - .:/var/www/app.dev
    networks:
      - skeleton-docker.network

  # apache:
  #   build: ./docker/apache
  #   restart: always
  #   container_name: skeleton-docker.apache
  #
  #   tty: true
  #   networks:
  #     - skeleton-docker.network
  #   depends_on:
  #     - php
  #     - mysql
  #     - postgres
  #     - redis
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - .:/var/www/app.dev

  #  mariadb:
  #    image: mariadb
  #    restart: always
  #    container_name: skeleton-docker.mariadb
  #
  #    tty: true
  #    networks:
  #      - skeleton-docker.network
  #    ports:
  #      - '3306:3306'
  #    volumes:
  #      - './docker/mysql/config/mariadb.cnf:/etc/mysql/conf.d/custom.cnf:ro'
  #      - './docker/mysql/dbdata:/var/lib/mysql'
  #    environment:
  #      - MYSQL_PASSWORD=root
  #      - MYSQL_ROOT_PASSWORD=root
  #      - MYSQL_DATABASE=development

  mysql:
    build: ./docker/mysql
    restart: always
    container_name: skeleton-docker.mysql

    tty: true
    networks:
      - skeleton-docker.network
    ports:
      - "3306:3306"
    volumes:
      - "./docker/mysql/config/mysql.cnf:/etc/mysql/conf.d/custom.cnf:ro"
      - "./docker/mysql/dbdata:/var/lib/mysql"
      - volumen-mysql:/var/lib/mysql
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=booking_bluetech

  phpmyadmin:
     image: library/phpmyadmin
     container_name: skeleton-docker.phpmyadmin
     tty: true
     networks:
       - skeleton-docker.network
     depends_on:
       - mysql
     environment:
        PMA_USER: root
        PMA_PASSWORD: root
        PMA_HOSTS: mysql
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
     ports:
       - '8090:80'

#  postgres:
#    build: ./docker/postgres
#    container_name: skeleton-docker.postgres
#    restart: always
#    tty: true
#    networks:
#      - skeleton-docker.network
#    ports:
#      - "5432:5432"
#    volumes:
#      - "./docker/postgres/dbdata:/var/lib/postgresql/data"
#    environment:
#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=root
#      - POSTGRES_DB=development

#  redis:
#    image: bitnami/redis:latest
#    restart: always
#    container_name: skeleton-docker.redis
#    tty: true
#    volumes:
#      - ./docker/redis:/bitnami/redis/data
#    networks:
#      - skeleton-docker.network
#    environment:
#      - ALLOW_EMPTY_PASSWORD=no
#      - REDIS_PASSWORD=root
#    ports:
#      - "6379:6379"


volumes:
  volumen-mysql:
