version: "3.7"

networks:
  skeleton-docker.network:
    driver: bridge

services:
  php:
    build: ./docker/php
    restart: always
    container_name: skeleton-docker.php
    tty: true
    depends_on:
      - mysql
    networks:
      - skeleton-docker.network
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/app.dev

  nginx:
    build: ./docker/nginx
    container_name: skeleton-docker.nginx
    restart: always
    tty: true
    depends_on:
      - php
      - mysql
    ports:
      - '8080:80'
      - "433:433"
    volumes:
      - .:/var/www/app.dev
    networks:
      - skeleton-docker.network

  mysql:
    build: ./docker/mysql
    restart: always
    container_name: skeleton-docker.mysql

    tty: true
    networks:
      - skeleton-docker.network
    ports:
      - "3306:3306"
    volumes:
      - volumen-mysql:/var/lib/mysql
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=booking_bluetech

  phpmyadmin:
     image: library/phpmyadmin
     container_name: skeleton-docker.phpmyadmin
     tty: true
     networks:
       - skeleton-docker.network
     depends_on:
       - mysql
     environment:
        PMA_USER: root
        PMA_PASSWORD: root
        PMA_HOSTS: mysql
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
     ports:
       - '8090:80'

volumes:
  volumen-mysql:
